### ISSUE TITLE
Is this official repository for MementoFX?

### ISSUE THREAD

**Issue by Liero** [MementoFX/MementoFX#1]
Is this official repository for MementoFX?

Will there be at least basic documentation and sample project?
Thanks

**Comment by andysal** [comment]
yes, this is the official repo: unfortunately, we still don't have documentation but we'll definitely make it available as soon as possible. In the meanwhile, you might want to have a look at Merp, which is the sample project we're actively developing: https://github.com/mastreeno/Merp
