### ISSUE TITLE
.NET Standard support

### ISSUE THREAD

**Issue by Liero** [MementoFX/MementoFX#3]
I would like to try this in .NET Core app. Is there a chance the libraries will be converted to .NET Standard 1.x in near future?

**Comment by andysal** [comment]
Hi Liero, we're aiming at supporting .NET Standard 2 as soon as it will go GA (in a couple of week, I think). Would that be ok for you or would you still need v1 support?

**Comment by Liero** [comment]
It should be ok, but is there something that prevents you from targeting 1.x at least for the base library?

**Comment by andysal** [comment]
the problem with targeting 1.x lies in the usage of a couple of Reflection features (e.g.: the GetUninitializedObject method sported by the FormatterServices class) which are neither provided by v1 nor replaceable without generating subtle breaking changes

**Comment by Liero** [comment]
Ok then
