### ISSUE TITLE
IEventStore.Find<T>(Expression<Func<T, bool>> filter) support

### ISSUE THREAD

**Issue by thunderluca** [MementoFX/MementoFX#6]
Hi all,

Currently, the `IEventStore` interface uses `System.Func<T, bool>` as parameter to filter events from event store implementation.

This filter type, however, doesn't allow to implement new persistance drivers (like, in my case, [LiteDB](https://github.com/mbdavid/LiteDB)) that support LINQ but with type `System.Linq.Expressions.Expression<Func<T, bool>>`, because of their engines's query translations that require expression trees.

I already tried to fork and change `IEventStore` interface with the desired type, successfully tested with "InMemory" solution (from MementoFX's tests project) and with MongoDB's driver.

I honestly haven't tried yet with RavenDB driver, but if it needs to be tested, I will try ASAP.

Let me know if this could be implemented or not.

Thanks in advance

**Comment by Liero** [comment]
I second this. It should be pretty easy refactoring.
I believe it was meant to be `Expression<Func<T, bool>>` from beginning. `Func<T, bool>` does not make much sense.

@thunderluca: maybe you can pullrequest?

**Comment by andysal** [comment]
guys, you definitely have a point. We were about to ship v2 but changing that method's signature does make sense so we're postponing the GA to try to include such (breaking) change. Re @thunderluca 's offer to test RavenDB, any contribution would be gladly accepted

**Comment by andysal** [comment]
PR was accepted and Nuget packages were updated accordingly starting from 2.0.0-pre6
